/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademicCalendarRouteImport } from './routes/academic-calendar'
import { Route as AcademicStructureRouteImport } from './routes/academic-structure'
import { Route as AddDropRouteImport } from './routes/add-drop'
import { Route as AdminReportsRouteImport } from './routes/admin-reports'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AtRiskStudentsRouteImport } from './routes/at-risk-students'
import { Route as ClassroomRouteImport } from './routes/classroom'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as GradeWorkflowRouteImport } from './routes/grade-workflow'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as LivePollsRouteImport } from './routes/live-polls'
import { Route as QuestionBankRouteImport } from './routes/question-bank'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as SendNotificationRouteImport } from './routes/send-notification'
import { Route as SmartPanelRouteImport } from './routes/smart-panel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicCalendarRoute = AcademicCalendarRouteImport.update({
  id: '/academic-calendar',
  path: '/academic-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicStructureRoute = AcademicStructureRouteImport.update({
  id: '/academic-structure',
  path: '/academic-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const AddDropRoute = AddDropRouteImport.update({
  id: '/add-drop',
  path: '/add-drop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin-reports',
  path: '/admin-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AtRiskStudentsRoute = AtRiskStudentsRouteImport.update({
  id: '/at-risk-students',
  path: '/at-risk-students',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomRoute = ClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const GradeWorkflowRoute = GradeWorkflowRouteImport.update({
  id: '/grade-workflow',
  path: '/grade-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const LivePollsRoute = LivePollsRouteImport.update({
  id: '/live-polls',
  path: '/live-polls',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankRoute = QuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const SendNotificationRoute = SendNotificationRouteImport.update({
  id: '/send-notification',
  path: '/send-notification',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartPanelRoute = SmartPanelRouteImport.update({
  id: '/smart-panel',
  path: '/smart-panel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/academic-structure': typeof AcademicStructureRoute
  '/add-drop': typeof AddDropRoute
  '/admin-reports': typeof AdminReportsRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/assignments': typeof AssignmentsRoute
  '/at-risk-students': typeof AtRiskStudentsRoute
  '/classroom': typeof ClassroomRoute
  '/courses': typeof CoursesRoute
  '/exams': typeof ExamsRoute
  '/grade-workflow': typeof GradeWorkflowRoute
  '/grades': typeof GradesRoute
  '/live-polls': typeof LivePollsRoute
  '/question-bank': typeof QuestionBankRoute
  '/requests': typeof RequestsRoute
  '/scheduling': typeof SchedulingRoute
  '/send-notification': typeof SendNotificationRoute
  '/smart-panel': typeof SmartPanelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/academic-structure': typeof AcademicStructureRoute
  '/add-drop': typeof AddDropRoute
  '/admin-reports': typeof AdminReportsRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/assignments': typeof AssignmentsRoute
  '/at-risk-students': typeof AtRiskStudentsRoute
  '/classroom': typeof ClassroomRoute
  '/courses': typeof CoursesRoute
  '/exams': typeof ExamsRoute
  '/grade-workflow': typeof GradeWorkflowRoute
  '/grades': typeof GradesRoute
  '/live-polls': typeof LivePollsRoute
  '/question-bank': typeof QuestionBankRoute
  '/requests': typeof RequestsRoute
  '/scheduling': typeof SchedulingRoute
  '/send-notification': typeof SendNotificationRoute
  '/smart-panel': typeof SmartPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/academic-structure': typeof AcademicStructureRoute
  '/add-drop': typeof AddDropRoute
  '/admin-reports': typeof AdminReportsRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/assignments': typeof AssignmentsRoute
  '/at-risk-students': typeof AtRiskStudentsRoute
  '/classroom': typeof ClassroomRoute
  '/courses': typeof CoursesRoute
  '/exams': typeof ExamsRoute
  '/grade-workflow': typeof GradeWorkflowRoute
  '/grades': typeof GradesRoute
  '/live-polls': typeof LivePollsRoute
  '/question-bank': typeof QuestionBankRoute
  '/requests': typeof RequestsRoute
  '/scheduling': typeof SchedulingRoute
  '/send-notification': typeof SendNotificationRoute
  '/smart-panel': typeof SmartPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-calendar'
    | '/academic-structure'
    | '/add-drop'
    | '/admin-reports'
    | '/ai-assistant'
    | '/assignments'
    | '/at-risk-students'
    | '/classroom'
    | '/courses'
    | '/exams'
    | '/grade-workflow'
    | '/grades'
    | '/live-polls'
    | '/question-bank'
    | '/requests'
    | '/scheduling'
    | '/send-notification'
    | '/smart-panel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-calendar'
    | '/academic-structure'
    | '/add-drop'
    | '/admin-reports'
    | '/ai-assistant'
    | '/assignments'
    | '/at-risk-students'
    | '/classroom'
    | '/courses'
    | '/exams'
    | '/grade-workflow'
    | '/grades'
    | '/live-polls'
    | '/question-bank'
    | '/requests'
    | '/scheduling'
    | '/send-notification'
    | '/smart-panel'
  id:
    | '__root__'
    | '/'
    | '/academic-calendar'
    | '/academic-structure'
    | '/add-drop'
    | '/admin-reports'
    | '/ai-assistant'
    | '/assignments'
    | '/at-risk-students'
    | '/classroom'
    | '/courses'
    | '/exams'
    | '/grade-workflow'
    | '/grades'
    | '/live-polls'
    | '/question-bank'
    | '/requests'
    | '/scheduling'
    | '/send-notification'
    | '/smart-panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicCalendarRoute: typeof AcademicCalendarRoute
  AcademicStructureRoute: typeof AcademicStructureRoute
  AddDropRoute: typeof AddDropRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AssignmentsRoute: typeof AssignmentsRoute
  AtRiskStudentsRoute: typeof AtRiskStudentsRoute
  ClassroomRoute: typeof ClassroomRoute
  CoursesRoute: typeof CoursesRoute
  ExamsRoute: typeof ExamsRoute
  GradeWorkflowRoute: typeof GradeWorkflowRoute
  GradesRoute: typeof GradesRoute
  LivePollsRoute: typeof LivePollsRoute
  QuestionBankRoute: typeof QuestionBankRoute
  RequestsRoute: typeof RequestsRoute
  SchedulingRoute: typeof SchedulingRoute
  SendNotificationRoute: typeof SendNotificationRoute
  SmartPanelRoute: typeof SmartPanelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-calendar': {
      id: '/academic-calendar'
      path: '/academic-calendar'
      fullPath: '/academic-calendar'
      preLoaderRoute: typeof AcademicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-structure': {
      id: '/academic-structure'
      path: '/academic-structure'
      fullPath: '/academic-structure'
      preLoaderRoute: typeof AcademicStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-drop': {
      id: '/add-drop'
      path: '/add-drop'
      fullPath: '/add-drop'
      preLoaderRoute: typeof AddDropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-reports': {
      id: '/admin-reports'
      path: '/admin-reports'
      fullPath: '/admin-reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/at-risk-students': {
      id: '/at-risk-students'
      path: '/at-risk-students'
      fullPath: '/at-risk-students'
      preLoaderRoute: typeof AtRiskStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom': {
      id: '/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof ClassroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-workflow': {
      id: '/grade-workflow'
      path: '/grade-workflow'
      fullPath: '/grade-workflow'
      preLoaderRoute: typeof GradeWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-polls': {
      id: '/live-polls'
      path: '/live-polls'
      fullPath: '/live-polls'
      preLoaderRoute: typeof LivePollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank': {
      id: '/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof QuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-notification': {
      id: '/send-notification'
      path: '/send-notification'
      fullPath: '/send-notification'
      preLoaderRoute: typeof SendNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-panel': {
      id: '/smart-panel'
      path: '/smart-panel'
      fullPath: '/smart-panel'
      preLoaderRoute: typeof SmartPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicCalendarRoute: AcademicCalendarRoute,
  AcademicStructureRoute: AcademicStructureRoute,
  AddDropRoute: AddDropRoute,
  AdminReportsRoute: AdminReportsRoute,
  AiAssistantRoute: AiAssistantRoute,
  AssignmentsRoute: AssignmentsRoute,
  AtRiskStudentsRoute: AtRiskStudentsRoute,
  ClassroomRoute: ClassroomRoute,
  CoursesRoute: CoursesRoute,
  ExamsRoute: ExamsRoute,
  GradeWorkflowRoute: GradeWorkflowRoute,
  GradesRoute: GradesRoute,
  LivePollsRoute: LivePollsRoute,
  QuestionBankRoute: QuestionBankRoute,
  RequestsRoute: RequestsRoute,
  SchedulingRoute: SchedulingRoute,
  SendNotificationRoute: SendNotificationRoute,
  SmartPanelRoute: SmartPanelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
